server:
  port: 9090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: jdbc:mysql://localhost:3306/crmdb
    username: root
    password: fadizoe1212
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# security
jwt:
  secret: "2y6gxzIUwMJKwF9L1tEsl8MdAop5k93TXxF35UlKq4gq"
  expiration: 86400000  # 1 day in milliseconds

